### ISSUE TITLE
No handling for elasticsearch cluster updates (rolling updates)

### ISSUE THREAD

**Issue by frankhetterich** [NETWAYS/ansible-collection-elasticstack#216]
We installed a Elasticsearch cluster using the collection in Version 8.8.1. After the successful installation we tried a update of the cluster to the (at the moment) latest version 8.9.0. 
It turned out that the collection is installing the new Elasticsearch version but does not restart the services afterwards so the node stays on the old version.
We investigated a bit deeper and it looks like there is no handling for a rolling cluster update at all. There is no serial restart of the services after an update and no cluster health check after a service restart implemented. 

Are there any plans to integrate these cluster update scenarios?

**Comment by widhalmt** [comment]
Exactly, the collection in its current form can't handle rolling cluster upgrades (or any form of upgrade, that is). So far, we are planning to have an option for upgrades but we haven't started implementing it. Since this procedure can have a lot of side effects we want to have a solution that's rock solid before we break anything.

We can keep this issue open so we won't forget the request when planning next releases.

**Comment by thorteschenk** [comment]
We also were very interested in having the functionality to update our cluster with the collection.
