### ISSUE TITLE
Elasticsearch jvm.options 

### ISSUE THREAD

**Issue by ivareri** [NETWAYS/ansible-collection-elasticstack#287]
Currently the `jvm.options` file is always installed, and some settings are always changed from the defaults. [Task](https://github.com/NETWAYS/ansible-collection-elasticstack/blob/62bf591a20234394a76ad43232bd846cb3206841/roles/elasticsearch/tasks/main.yml#L163C1-L163C2) , [template](https://github.com/NETWAYS/ansible-collection-elasticstack/blob/main/roles/elasticsearch/templates/jvm.options.j2)

There are 3 groups of changes, that ideally would get separate files in `jvm.options.d`. 

* heap size
`Xms` and `Xmx`  is always set. The current [recommendation](https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html#set-jvm-heap-size) is to leave the heap size settings in the default value. I'd like this to be an optional setting. 

* Paths
All changes to log paths, etc. 

* Custom options
Settings from `elasticsearch_jvm_custom_parameters`.  Should have a filename to ensure it is processed last.

* Defaults that shouldn't be set
`-XX:+UseG1GC`, `-Djava.io.tmpdir=${ES_TMPDIR}`, `20:--add-modules=jdk.incubator.vector`, `-XX:+HeapDumpOnOutOfMemoryError`, and `-XX:+ExitOnOutOfMemoryError` is unchanged from the default settings, so they can be removed from the template.

**Comment by widhalmt** [comment]
Hm... having it split up into several files would totally make sense for managing it with Ansible. Thanks, that's a good idea. 

The default for Heap size changes more often than the weather in my experience. You're totally right that currently it's to not change it at all. Most projects at our customers use systems where a lot of memory would be wasted if we stayed with it. Keeping it to the default as an option is doable. What we now have is overriding the calculated value. So you would have to put in the default yourself. Would that be sufficient or would you like to have a variable to go back to the current default?

Also, I like the idea of having custom parameters. What about something like https://github.com/NETWAYS/ansible-collection-elasticstack/blob/main/docs/role-kibana.md?plain=1#L16 so you can add arbitrary configuration via a variable?

Overriding defaults with defaults isn't very useful when working with configuration management, you're right. Especially since we try to cover different versions and the default values differ from version to version.

**Comment by ivareri** [comment]
> The default for Heap size changes more often than the weather in my experience. You're totally right that currently it's to not change it at all. Most projects at our customers use systems where a lot of memory would be wasted if we stayed with it. Keeping it to the default as an option is doable. What we now have is overriding the calculated value. So you would have to put in the default yourself. Would that be sufficient or would you like to have a variable to go back to the current default?

My preferred solution to heap setting would be: 
- Not set  `elasticsearch_heap`  in [`defaults/main.yml`](https://github.com/NETWAYS/ansible-collection-elasticstack/blob/60115d101e3522ab13dcbb4c5704f1e1aa19952e/roles/elasticsearch/defaults/main.yml#L17C1-L17C19)
- Have a task that adds a `heap.options` file to `jvm.options.d/` if, and only if, `elasticsearch_heap` is set

The `heap.options` template would then be something like 

```
# Xms represents the initial size of total heap space
# Xmx represents the maximum size of total heap space
-Xms{{ elasticsearch_heap }}
-Xmx{{ elasticsearch_heap }}
``` 
I'm not quite sure I follow the current default for `elasticsearch_heap`.  It sets it to half the size of host_memory, with upper limit of 30gig and lower limit of 1gig?


> Also, I like the idea of having custom parameters. What about something like https://github.com/NETWAYS/ansible-collection-elasticstack/blob/main/docs/role-kibana.md?plain=1#L16 so you can add arbitrary configuration via a variable?
> 
Yeah, something like would be great. A similar setting for `elasticsearch.yml` config would also make sense :)
