### ISSUE TITLE
elasticsearch as a group name

### ISSUE THREAD

**Issue by afeefghannam89** [NETWAYS/ansible-collection-elasticstack#31]
We should replace the elasticsearuch as a group name in the [elasticsearch.yml.j2](https://github.com/NETWAYS/ansible-collection-elasticstack/blob/main/roles/elasticsearch/templates/elasticsearch.yml.j2) with something like **ansible_play_hosts_all**. OR point out in the README that the group name have to be elasticsearch.

**Comment by widhalmt** [comment]
Yes! I don't want to use `all`, because with groups a user can manage different host of groups. You can run all roles on all hosts and depending on the group memberships some become Elasticsearch hosts, some Logstash hosts etc. . The idea to run it on "all" is to be able to access one Elasticsearch host as "CA Host" even from within the Logstash or Beats role.

If you find a better way, it's always welcome. I hate that I had to go with hardcoded groups but I didn't find anything else that worked.

**Comment by afeefghannam89** [comment]
You are right logstash group for example will be involved if we use **all**.
